# Generated by Django 4.2.23 on 2026-02-20 21:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CierreDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('valor_palet', models.DecimalField(decimal_places=2, default=1.0, help_text='USD por palet', max_digits=6)),
                ('total_palets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cierre de Día',
                'verbose_name_plural': 'Cierres de Día',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('papel', '🧻 Papel / Higiene'), ('alimentos', '🌾 Alimentos secos'), ('bebidas', '🧃 Bebidas'), ('lacteos', '🥛 Lácteos'), ('limpieza', '🧹 Limpieza'), ('aceites', '🫙 Aceites / Grasas'), ('snacks', '🍪 Snacks / Confitería'), ('otros', '📦 Otros')], default='otros', max_length=20)),
                ('unidades_por_capa', models.PositiveIntegerField(default=8)),
                ('capas_por_palet', models.PositiveIntegerField(default=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('conductor', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDescargue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('especial', 'Especial')], default='completo', max_length=12)),
                ('palets_completos', models.PositiveIntegerField(default=0)),
                ('unidades_sueltas', models.PositiveIntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='Descargue.cierredia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargues', to='Descargue.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargues', to='Descargue.proveedor')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-hora'],
            },
        ),
    ]
