# Generated by Django 4.2.23 on 2026-02-20 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Descargue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemDescargue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palets_completos', models.PositiveIntegerField(default=0)),
                ('unidades_sueltas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ítem de Descargue',
                'verbose_name_plural': 'Ítems de Descargue',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='registrodescargue',
            options={'ordering': ['-hora'], 'verbose_name': 'Registro de Descargue', 'verbose_name_plural': 'Registros de Descargue'},
        ),
        migrations.RemoveField(
            model_name='cierredia',
            name='total_usd',
        ),
        migrations.RemoveField(
            model_name='cierredia',
            name='valor_palet',
        ),
        migrations.RemoveField(
            model_name='registrodescargue',
            name='palets_completos',
        ),
        migrations.RemoveField(
            model_name='registrodescargue',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='registrodescargue',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='registrodescargue',
            name='unidades_sueltas',
        ),
        migrations.AddField(
            model_name='registrodescargue',
            name='chofer_nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registrodescargue',
            name='chofer_telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registrodescargue',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='registrodescargue',
            name='hora_fin_estimada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodescargue',
            name='placa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.AddField(
            model_name='itemdescargue',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Descargue.producto'),
        ),
        migrations.AddField(
            model_name='itemdescargue',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Descargue.registrodescargue'),
        ),
        migrations.AddField(
            model_name='registrodescargue',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargues', to='Descargue.empresa'),
        ),
    ]
