# Generated by Django 4.2.23 on 2025-12-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='turno',
            field=models.CharField(choices=[('TURNO_1', '5:00 AM - 11:00 AM'), ('TURNO_2', '6:00 AM - 2:30 PM')], default='TURNO_1', max_length=10, verbose_name='Turno'),
        ),
    ]
