# Generated by Django 4.2.23 on 2025-12-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0002_empleado_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='registro_completo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='turno',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(default='05:00:00', verbose_name='Hora de Entrada'),
            preserve_default=False,
        ),
    ]
